server:
  port: 8082

spring:
  application:
    name: user-service

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    config:
      fail-fast: false

  datasource:
    url: jdbc:postgresql://postgres:5432/company_db
    username: aliya
    password: aliya123
    driver-class-name: org.postgresql.Driver