server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aliyagabbassova/spring-cloud-config-repo.git
          skip-ssl-validation: true
          default-label: main
          clone-on-start: true
          force-pull: true
      fail-fast: true
  profiles:
    active: git

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
