server:
  port: 8083

spring:
  application:
    name: gateway

  #  config:
  #    import: optional:configserver:http://config-server:8888

  cloud:
    config:
      uri: http://config-server:8888
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/company_db/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
